// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Adverseevent struct {
	ID                     int32       `json:"id"`
	ProductID              pgtype.Int4 `json:"product_id"`
	EventDate              pgtype.Date `json:"event_date"`
	Description            pgtype.Text `json:"description"`
	Severity               pgtype.Text `json:"severity"`
	RegulatoryReportStatus pgtype.Text `json:"regulatory_report_status"`
}

type Audit struct {
	ID            int32       `json:"id"`
	AuditType     pgtype.Text `json:"audit_type"`
	ScheduledDate pgtype.Date `json:"scheduled_date"`
	ActualDate    pgtype.Date `json:"actual_date"`
	AuditorID     pgtype.Int4 `json:"auditor_id"`
	Status        pgtype.Text `json:"status"`
}

type Auditfinding struct {
	ID               int32       `json:"id"`
	AuditID          pgtype.Int4 `json:"audit_id"`
	Description      pgtype.Text `json:"description"`
	Severity         pgtype.Text `json:"severity"`
	CorrectiveAction pgtype.Text `json:"corrective_action"`
	DueDate          pgtype.Date `json:"due_date"`
	Status           pgtype.Text `json:"status"`
}

type Capa struct {
	ID                 int32       `json:"id"`
	NonconformanceID   pgtype.Int4 `json:"nonconformance_id"`
	RootCause          pgtype.Text `json:"root_cause"`
	CorrectiveAction   pgtype.Text `json:"corrective_action"`
	PreventiveAction   pgtype.Text `json:"preventive_action"`
	ProposedDate       pgtype.Date `json:"proposed_date"`
	CompletionDate     pgtype.Date `json:"completion_date"`
	EffectivenessCheck pgtype.Text `json:"effectiveness_check"`
	Status             pgtype.Text `json:"status"`
}

type Complaint struct {
	ID             int32       `json:"id"`
	CustomerName   pgtype.Text `json:"customer_name"`
	ProductID      pgtype.Int4 `json:"product_id"`
	BatchLotNumber pgtype.Text `json:"batch_lot_number"`
	ComplaintDate  pgtype.Date `json:"complaint_date"`
	Description    pgtype.Text `json:"description"`
	Status         pgtype.Text `json:"status"`
}

type Complaintinvestigation struct {
	ID                int32       `json:"id"`
	ComplaintID       pgtype.Int4 `json:"complaint_id"`
	RootCause         pgtype.Text `json:"root_cause"`
	CorrectiveAction  pgtype.Text `json:"corrective_action"`
	InvestigatorID    pgtype.Int4 `json:"investigator_id"`
	InvestigationDate pgtype.Date `json:"investigation_date"`
}

type Designproject struct {
	ID                     int32       `json:"id"`
	ProjectName            pgtype.Text `json:"project_name"`
	StartDate              pgtype.Date `json:"start_date"`
	ExpectedCompletionDate pgtype.Date `json:"expected_completion_date"`
	Status                 pgtype.Text `json:"status"`
}

type Designrequirement struct {
	ID                     int32       `json:"id"`
	ProjectID              pgtype.Int4 `json:"project_id"`
	RequirementDescription pgtype.Text `json:"requirement_description"`
	RequirementType        pgtype.Text `json:"requirement_type"`
}

type Designverification struct {
	ID                 int32            `json:"id"`
	RequirementID      pgtype.Int4      `json:"requirement_id"`
	VerificationMethod pgtype.Text      `json:"verification_method"`
	VerificationResult pgtype.Text      `json:"verification_result"`
	VerifiedBy         pgtype.Int4      `json:"verified_by"`
	VerificationDate   pgtype.Timestamp `json:"verification_date"`
}

type Document struct {
	ID               int32            `json:"id"`
	DocumentType     pgtype.Text      `json:"document_type"`
	Title            string           `json:"title"`
	Version          string           `json:"version"`
	CreatedBy        pgtype.Int4      `json:"created_by"`
	CreatedDate      pgtype.Timestamp `json:"created_date"`
	LastReviewedDate pgtype.Timestamp `json:"last_reviewed_date"`
	NextReviewDate   pgtype.Timestamp `json:"next_review_date"`
	Status           pgtype.Text      `json:"status"`
	Content          pgtype.Text      `json:"content"`
}

type Documentaudittrail struct {
	ID              int32            `json:"id"`
	DocumentID      pgtype.Int4      `json:"document_id"`
	ActionType      pgtype.Text      `json:"action_type"`
	ActionBy        pgtype.Int4      `json:"action_by"`
	ActionDate      pgtype.Timestamp `json:"action_date"`
	PreviousVersion pgtype.Text      `json:"previous_version"`
}

type Nonconformance struct {
	ID           int32       `json:"id"`
	Description  pgtype.Text `json:"description"`
	DetectedDate pgtype.Date `json:"detected_date"`
	DetectedBy   pgtype.Int4 `json:"detected_by"`
	ProductID    pgtype.Int4 `json:"product_id"`
	Severity     pgtype.Text `json:"severity"`
	Status       pgtype.Text `json:"status"`
}

type Riskregister struct {
	ID                 int32          `json:"id"`
	RiskName           pgtype.Text    `json:"risk_name"`
	Description        pgtype.Text    `json:"description"`
	RiskLevel          pgtype.Text    `json:"risk_level"`
	Likelihood         pgtype.Numeric `json:"likelihood"`
	Impact             pgtype.Numeric `json:"impact"`
	RiskScore          pgtype.Numeric `json:"risk_score"`
	MitigationStrategy pgtype.Text    `json:"mitigation_strategy"`
	CurrentStatus      pgtype.Text    `json:"current_status"`
	OwnerID            pgtype.Int4    `json:"owner_id"`
}

type Supplier struct {
	ID                  int32       `json:"id"`
	SupplierName        pgtype.Text `json:"supplier_name"`
	ContactPerson       pgtype.Text `json:"contact_person"`
	Email               pgtype.Text `json:"email"`
	Phone               pgtype.Text `json:"phone"`
	QualificationStatus pgtype.Text `json:"qualification_status"`
	LastEvaluatedDate   pgtype.Date `json:"last_evaluated_date"`
}

type Supplierperformance struct {
	ID             int32          `json:"id"`
	SupplierID     pgtype.Int4    `json:"supplier_id"`
	EvaluationDate pgtype.Date    `json:"evaluation_date"`
	OverallScore   pgtype.Numeric `json:"overall_score"`
	QualityRating  pgtype.Numeric `json:"quality_rating"`
	DeliveryRating pgtype.Numeric `json:"delivery_rating"`
	Comments       pgtype.Text    `json:"comments"`
}

type Systemaccesslog struct {
	ID         int32            `json:"id"`
	UserID     pgtype.Int4      `json:"user_id"`
	ActionType pgtype.Text      `json:"action_type"`
	Timestamp  pgtype.Timestamp `json:"timestamp"`
	IpAddress  pgtype.Text      `json:"ip_address"`
}

type Trainingmatrix struct {
	RoleID     int32       `json:"role_id"`
	TrainingID int32       `json:"training_id"`
	IsRequired pgtype.Bool `json:"is_required"`
}

type Trainingrecord struct {
	ID                int32       `json:"id"`
	UserID            pgtype.Int4 `json:"user_id"`
	TrainingName      pgtype.Text `json:"training_name"`
	CompletionDate    pgtype.Date `json:"completion_date"`
	ExpiryDate        pgtype.Date `json:"expiry_date"`
	CertificateNumber pgtype.Text `json:"certificate_number"`
}

type User struct {
	ID        int32            `json:"id"`
	Username  string           `json:"username"`
	Email     string           `json:"email"`
	RoleID    int32            `json:"role_id"`
	LastLogin pgtype.Timestamp `json:"last_login"`
	IsActive  pgtype.Bool      `json:"is_active"`
}

type Userpermission struct {
	RoleID         int32  `json:"role_id"`
	PermissionCode string `json:"permission_code"`
}

type Userrole struct {
	ID          int32       `json:"id"`
	RoleName    string      `json:"role_name"`
	Description pgtype.Text `json:"description"`
}
