// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (int32, error)
	GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error)
	SeedRoles(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
