// Code generated by mockery v2.49.1. DO NOT EDIT.

package handler

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// MockUserHandler is an autogenerated mock type for the UserHandler type
type MockUserHandler struct {
	mock.Mock
}

type MockUserHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserHandler) EXPECT() *MockUserHandler_Expecter {
	return &MockUserHandler_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: c
func (_m *MockUserHandler) CreateUser(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserHandler_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserHandler_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockUserHandler_Expecter) CreateUser(c interface{}) *MockUserHandler_CreateUser_Call {
	return &MockUserHandler_CreateUser_Call{Call: _e.mock.On("CreateUser", c)}
}

func (_c *MockUserHandler_CreateUser_Call) Run(run func(c echo.Context)) *MockUserHandler_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *MockUserHandler_CreateUser_Call) Return(_a0 error) *MockUserHandler_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserHandler_CreateUser_Call) RunAndReturn(run func(echo.Context) error) *MockUserHandler_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function with given fields: c
func (_m *MockUserHandler) GetAllUsers(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserHandler_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type MockUserHandler_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockUserHandler_Expecter) GetAllUsers(c interface{}) *MockUserHandler_GetAllUsers_Call {
	return &MockUserHandler_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers", c)}
}

func (_c *MockUserHandler_GetAllUsers_Call) Run(run func(c echo.Context)) *MockUserHandler_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *MockUserHandler_GetAllUsers_Call) Return(_a0 error) *MockUserHandler_GetAllUsers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserHandler_GetAllUsers_Call) RunAndReturn(run func(echo.Context) error) *MockUserHandler_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserHandler creates a new instance of MockUserHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserHandler {
	mock := &MockUserHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
